/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.payloads;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WebPromo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WebPromo\",\"namespace\":\"maestro.payloads\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.payloads.WebPromo\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"available_from\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"available_to\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"use_external_browser\",\"type\":\"boolean\"},{\"name\":\"language\",\"type\":\"string\"},{\"name\":\"thumbnail_image_s3_key\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"link_url\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence type;
  @Deprecated public int id;
  @Deprecated public long available_from;
  @Deprecated public long available_to;
  @Deprecated public boolean use_external_browser;
  @Deprecated public CharSequence language;
  @Deprecated public CharSequence thumbnail_image_s3_key;
  @Deprecated public CharSequence name;
  @Deprecated public CharSequence link_url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WebPromo() {}

  /**
   * All-args constructor.
   */
  public WebPromo(CharSequence type, Integer id, Long available_from, Long available_to, Boolean use_external_browser, CharSequence language, CharSequence thumbnail_image_s3_key, CharSequence name, CharSequence link_url) {
    this.type = type;
    this.id = id;
    this.available_from = available_from;
    this.available_to = available_to;
    this.use_external_browser = use_external_browser;
    this.language = language;
    this.thumbnail_image_s3_key = thumbnail_image_s3_key;
    this.name = name;
    this.link_url = link_url;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return id;
    case 2: return available_from;
    case 3: return available_to;
    case 4: return use_external_browser;
    case 5: return language;
    case 6: return thumbnail_image_s3_key;
    case 7: return name;
    case 8: return link_url;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: type = (CharSequence)value$; break;
    case 1: id = (Integer)value$; break;
    case 2: available_from = (Long)value$; break;
    case 3: available_to = (Long)value$; break;
    case 4: use_external_browser = (Boolean)value$; break;
    case 5: language = (CharSequence)value$; break;
    case 6: thumbnail_image_s3_key = (CharSequence)value$; break;
    case 7: name = (CharSequence)value$; break;
    case 8: link_url = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'available_from' field.
   */
  public Long getAvailableFrom() {
    return available_from;
  }

  /**
   * Sets the value of the 'available_from' field.
   * @param value the value to set.
   */
  public void setAvailableFrom(Long value) {
    this.available_from = value;
  }

  /**
   * Gets the value of the 'available_to' field.
   */
  public Long getAvailableTo() {
    return available_to;
  }

  /**
   * Sets the value of the 'available_to' field.
   * @param value the value to set.
   */
  public void setAvailableTo(Long value) {
    this.available_to = value;
  }

  /**
   * Gets the value of the 'use_external_browser' field.
   */
  public Boolean getUseExternalBrowser() {
    return use_external_browser;
  }

  /**
   * Sets the value of the 'use_external_browser' field.
   * @param value the value to set.
   */
  public void setUseExternalBrowser(Boolean value) {
    this.use_external_browser = value;
  }

  /**
   * Gets the value of the 'language' field.
   */
  public CharSequence getLanguage() {
    return language;
  }

  /**
   * Sets the value of the 'language' field.
   * @param value the value to set.
   */
  public void setLanguage(CharSequence value) {
    this.language = value;
  }

  /**
   * Gets the value of the 'thumbnail_image_s3_key' field.
   */
  public CharSequence getThumbnailImageS3Key() {
    return thumbnail_image_s3_key;
  }

  /**
   * Sets the value of the 'thumbnail_image_s3_key' field.
   * @param value the value to set.
   */
  public void setThumbnailImageS3Key(CharSequence value) {
    this.thumbnail_image_s3_key = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'link_url' field.
   */
  public CharSequence getLinkUrl() {
    return link_url;
  }

  /**
   * Sets the value of the 'link_url' field.
   * @param value the value to set.
   */
  public void setLinkUrl(CharSequence value) {
    this.link_url = value;
  }

  /** Creates a new WebPromo RecordBuilder */
  public static maestro.payloads.WebPromo.Builder newBuilder() {
    return new maestro.payloads.WebPromo.Builder();
  }

  /** Creates a new WebPromo RecordBuilder by copying an existing Builder */
  public static maestro.payloads.WebPromo.Builder newBuilder(maestro.payloads.WebPromo.Builder other) {
    return new maestro.payloads.WebPromo.Builder(other);
  }

  /** Creates a new WebPromo RecordBuilder by copying an existing WebPromo instance */
  public static maestro.payloads.WebPromo.Builder newBuilder(maestro.payloads.WebPromo other) {
    return new maestro.payloads.WebPromo.Builder(other);
  }

  /**
   * RecordBuilder for WebPromo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WebPromo>
    implements org.apache.avro.data.RecordBuilder<WebPromo> {

    private CharSequence type;
    private int id;
    private long available_from;
    private long available_to;
    private boolean use_external_browser;
    private CharSequence language;
    private CharSequence thumbnail_image_s3_key;
    private CharSequence name;
    private CharSequence link_url;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.payloads.WebPromo.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.payloads.WebPromo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.available_from)) {
        this.available_from = data().deepCopy(fields()[2].schema(), other.available_from);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.available_to)) {
        this.available_to = data().deepCopy(fields()[3].schema(), other.available_to);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.use_external_browser)) {
        this.use_external_browser = data().deepCopy(fields()[4].schema(), other.use_external_browser);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.language)) {
        this.language = data().deepCopy(fields()[5].schema(), other.language);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.thumbnail_image_s3_key)) {
        this.thumbnail_image_s3_key = data().deepCopy(fields()[6].schema(), other.thumbnail_image_s3_key);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.name)) {
        this.name = data().deepCopy(fields()[7].schema(), other.name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.link_url)) {
        this.link_url = data().deepCopy(fields()[8].schema(), other.link_url);
        fieldSetFlags()[8] = true;
      }
    }

    /** Creates a Builder by copying an existing WebPromo instance */
    private Builder(maestro.payloads.WebPromo other) {
            super(maestro.payloads.WebPromo.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.available_from)) {
        this.available_from = data().deepCopy(fields()[2].schema(), other.available_from);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.available_to)) {
        this.available_to = data().deepCopy(fields()[3].schema(), other.available_to);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.use_external_browser)) {
        this.use_external_browser = data().deepCopy(fields()[4].schema(), other.use_external_browser);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.language)) {
        this.language = data().deepCopy(fields()[5].schema(), other.language);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.thumbnail_image_s3_key)) {
        this.thumbnail_image_s3_key = data().deepCopy(fields()[6].schema(), other.thumbnail_image_s3_key);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.name)) {
        this.name = data().deepCopy(fields()[7].schema(), other.name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.link_url)) {
        this.link_url = data().deepCopy(fields()[8].schema(), other.link_url);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public maestro.payloads.WebPromo.Builder setType(CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'type' field */
    public maestro.payloads.WebPromo.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public Integer getId() {
      return id;
    }

    /** Sets the value of the 'id' field */
    public maestro.payloads.WebPromo.Builder setId(int value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'id' field */
    public maestro.payloads.WebPromo.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'available_from' field */
    public Long getAvailableFrom() {
      return available_from;
    }

    /** Sets the value of the 'available_from' field */
    public maestro.payloads.WebPromo.Builder setAvailableFrom(long value) {
      validate(fields()[2], value);
      this.available_from = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'available_from' field has been set */
    public boolean hasAvailableFrom() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'available_from' field */
    public maestro.payloads.WebPromo.Builder clearAvailableFrom() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'available_to' field */
    public Long getAvailableTo() {
      return available_to;
    }

    /** Sets the value of the 'available_to' field */
    public maestro.payloads.WebPromo.Builder setAvailableTo(long value) {
      validate(fields()[3], value);
      this.available_to = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'available_to' field has been set */
    public boolean hasAvailableTo() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'available_to' field */
    public maestro.payloads.WebPromo.Builder clearAvailableTo() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'use_external_browser' field */
    public Boolean getUseExternalBrowser() {
      return use_external_browser;
    }

    /** Sets the value of the 'use_external_browser' field */
    public maestro.payloads.WebPromo.Builder setUseExternalBrowser(boolean value) {
      validate(fields()[4], value);
      this.use_external_browser = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'use_external_browser' field has been set */
    public boolean hasUseExternalBrowser() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'use_external_browser' field */
    public maestro.payloads.WebPromo.Builder clearUseExternalBrowser() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'language' field */
    public CharSequence getLanguage() {
      return language;
    }

    /** Sets the value of the 'language' field */
    public maestro.payloads.WebPromo.Builder setLanguage(CharSequence value) {
      validate(fields()[5], value);
      this.language = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /** Checks whether the 'language' field has been set */
    public boolean hasLanguage() {
      return fieldSetFlags()[5];
    }

    /** Clears the value of the 'language' field */
    public maestro.payloads.WebPromo.Builder clearLanguage() {
      language = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'thumbnail_image_s3_key' field */
    public CharSequence getThumbnailImageS3Key() {
      return thumbnail_image_s3_key;
    }

    /** Sets the value of the 'thumbnail_image_s3_key' field */
    public maestro.payloads.WebPromo.Builder setThumbnailImageS3Key(CharSequence value) {
      validate(fields()[6], value);
      this.thumbnail_image_s3_key = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /** Checks whether the 'thumbnail_image_s3_key' field has been set */
    public boolean hasThumbnailImageS3Key() {
      return fieldSetFlags()[6];
    }

    /** Clears the value of the 'thumbnail_image_s3_key' field */
    public maestro.payloads.WebPromo.Builder clearThumbnailImageS3Key() {
      thumbnail_image_s3_key = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public CharSequence getName() {
      return name;
    }

    /** Sets the value of the 'name' field */
    public maestro.payloads.WebPromo.Builder setName(CharSequence value) {
      validate(fields()[7], value);
      this.name = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[7];
    }

    /** Clears the value of the 'name' field */
    public maestro.payloads.WebPromo.Builder clearName() {
      name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'link_url' field */
    public CharSequence getLinkUrl() {
      return link_url;
    }

    /** Sets the value of the 'link_url' field */
    public maestro.payloads.WebPromo.Builder setLinkUrl(CharSequence value) {
      validate(fields()[8], value);
      this.link_url = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /** Checks whether the 'link_url' field has been set */
    public boolean hasLinkUrl() {
      return fieldSetFlags()[8];
    }

    /** Clears the value of the 'link_url' field */
    public maestro.payloads.WebPromo.Builder clearLinkUrl() {
      link_url = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public WebPromo build() {
      try {
        WebPromo record = new WebPromo();
        record.type = fieldSetFlags()[0] ? this.type : (CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (Integer) defaultValue(fields()[1]);
        record.available_from = fieldSetFlags()[2] ? this.available_from : (Long) defaultValue(fields()[2]);
        record.available_to = fieldSetFlags()[3] ? this.available_to : (Long) defaultValue(fields()[3]);
        record.use_external_browser = fieldSetFlags()[4] ? this.use_external_browser : (Boolean) defaultValue(fields()[4]);
        record.language = fieldSetFlags()[5] ? this.language : (CharSequence) defaultValue(fields()[5]);
        record.thumbnail_image_s3_key = fieldSetFlags()[6] ? this.thumbnail_image_s3_key : (CharSequence) defaultValue(fields()[6]);
        record.name = fieldSetFlags()[7] ? this.name : (CharSequence) defaultValue(fields()[7]);
        record.link_url = fieldSetFlags()[8] ? this.link_url : (CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
