/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.components;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Banner extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Banner\",\"namespace\":\"maestro.components\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.Banner\"},{\"name\":\"image_url\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"link\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence type;
  @Deprecated public CharSequence image_url;
  @Deprecated public CharSequence label;
  @Deprecated public CharSequence link;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Banner() {}

  /**
   * All-args constructor.
   */
  public Banner(CharSequence type, CharSequence image_url, CharSequence label, CharSequence link) {
    this.type = type;
    this.image_url = image_url;
    this.label = label;
    this.link = link;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return image_url;
    case 2: return label;
    case 3: return link;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: type = (CharSequence)value$; break;
    case 1: image_url = (CharSequence)value$; break;
    case 2: label = (CharSequence)value$; break;
    case 3: link = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'image_url' field.
   */
  public CharSequence getImageUrl() {
    return image_url;
  }

  /**
   * Sets the value of the 'image_url' field.
   * @param value the value to set.
   */
  public void setImageUrl(CharSequence value) {
    this.image_url = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'link' field.
   */
  public CharSequence getLink() {
    return link;
  }

  /**
   * Sets the value of the 'link' field.
   * @param value the value to set.
   */
  public void setLink(CharSequence value) {
    this.link = value;
  }

  /** Creates a new Banner RecordBuilder */
  public static maestro.components.Banner.Builder newBuilder() {
    return new maestro.components.Banner.Builder();
  }

  /** Creates a new Banner RecordBuilder by copying an existing Builder */
  public static maestro.components.Banner.Builder newBuilder(maestro.components.Banner.Builder other) {
    return new maestro.components.Banner.Builder(other);
  }

  /** Creates a new Banner RecordBuilder by copying an existing Banner instance */
  public static maestro.components.Banner.Builder newBuilder(maestro.components.Banner other) {
    return new maestro.components.Banner.Builder(other);
  }

  /**
   * RecordBuilder for Banner instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Banner>
    implements org.apache.avro.data.RecordBuilder<Banner> {

    private CharSequence type;
    private CharSequence image_url;
    private CharSequence label;
    private CharSequence link;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.components.Banner.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.components.Banner.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.image_url)) {
        this.image_url = data().deepCopy(fields()[1].schema(), other.image_url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.link)) {
        this.link = data().deepCopy(fields()[3].schema(), other.link);
        fieldSetFlags()[3] = true;
      }
    }

    /** Creates a Builder by copying an existing Banner instance */
    private Builder(maestro.components.Banner other) {
            super(maestro.components.Banner.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.image_url)) {
        this.image_url = data().deepCopy(fields()[1].schema(), other.image_url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.link)) {
        this.link = data().deepCopy(fields()[3].schema(), other.link);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public maestro.components.Banner.Builder setType(CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'type' field */
    public maestro.components.Banner.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'image_url' field */
    public CharSequence getImageUrl() {
      return image_url;
    }

    /** Sets the value of the 'image_url' field */
    public maestro.components.Banner.Builder setImageUrl(CharSequence value) {
      validate(fields()[1], value);
      this.image_url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'image_url' field has been set */
    public boolean hasImageUrl() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'image_url' field */
    public maestro.components.Banner.Builder clearImageUrl() {
      image_url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public CharSequence getLabel() {
      return label;
    }

    /** Sets the value of the 'label' field */
    public maestro.components.Banner.Builder setLabel(CharSequence value) {
      validate(fields()[2], value);
      this.label = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'label' field */
    public maestro.components.Banner.Builder clearLabel() {
      label = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'link' field */
    public CharSequence getLink() {
      return link;
    }

    /** Sets the value of the 'link' field */
    public maestro.components.Banner.Builder setLink(CharSequence value) {
      validate(fields()[3], value);
      this.link = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'link' field has been set */
    public boolean hasLink() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'link' field */
    public maestro.components.Banner.Builder clearLink() {
      link = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Banner build() {
      try {
        Banner record = new Banner();
        record.type = fieldSetFlags()[0] ? this.type : (CharSequence) defaultValue(fields()[0]);
        record.image_url = fieldSetFlags()[1] ? this.image_url : (CharSequence) defaultValue(fields()[1]);
        record.label = fieldSetFlags()[2] ? this.label : (CharSequence) defaultValue(fields()[2]);
        record.link = fieldSetFlags()[3] ? this.link : (CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
