/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.components;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GoogleNativeAd extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GoogleNativeAd\",\"namespace\":\"maestro.components\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.GoogleNativeAd\"},{\"name\":\"unit_id\",\"type\":\"string\"},{\"name\":\"location\",\"type\":\"boolean\"},{\"name\":\"custom_targetting\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"string\"}},\"default\":{}},{\"name\":\"cache_key\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence type;
  @Deprecated public CharSequence unit_id;
  @Deprecated public boolean location;
  @Deprecated public java.util.Map<CharSequence,java.util.List<CharSequence>> custom_targetting;
  @Deprecated public CharSequence cache_key;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GoogleNativeAd() {}

  /**
   * All-args constructor.
   */
  public GoogleNativeAd(CharSequence type, CharSequence unit_id, Boolean location, java.util.Map<CharSequence,java.util.List<CharSequence>> custom_targetting, CharSequence cache_key) {
    this.type = type;
    this.unit_id = unit_id;
    this.location = location;
    this.custom_targetting = custom_targetting;
    this.cache_key = cache_key;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return unit_id;
    case 2: return location;
    case 3: return custom_targetting;
    case 4: return cache_key;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: type = (CharSequence)value$; break;
    case 1: unit_id = (CharSequence)value$; break;
    case 2: location = (Boolean)value$; break;
    case 3: custom_targetting = (java.util.Map<CharSequence,java.util.List<CharSequence>>)value$; break;
    case 4: cache_key = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'unit_id' field.
   */
  public CharSequence getUnitId() {
    return unit_id;
  }

  /**
   * Sets the value of the 'unit_id' field.
   * @param value the value to set.
   */
  public void setUnitId(CharSequence value) {
    this.unit_id = value;
  }

  /**
   * Gets the value of the 'location' field.
   */
  public Boolean getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(Boolean value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'custom_targetting' field.
   */
  public java.util.Map<CharSequence,java.util.List<CharSequence>> getCustomTargetting() {
    return custom_targetting;
  }

  /**
   * Sets the value of the 'custom_targetting' field.
   * @param value the value to set.
   */
  public void setCustomTargetting(java.util.Map<CharSequence,java.util.List<CharSequence>> value) {
    this.custom_targetting = value;
  }

  /**
   * Gets the value of the 'cache_key' field.
   */
  public CharSequence getCacheKey() {
    return cache_key;
  }

  /**
   * Sets the value of the 'cache_key' field.
   * @param value the value to set.
   */
  public void setCacheKey(CharSequence value) {
    this.cache_key = value;
  }

  /** Creates a new GoogleNativeAd RecordBuilder */
  public static maestro.components.GoogleNativeAd.Builder newBuilder() {
    return new maestro.components.GoogleNativeAd.Builder();
  }

  /** Creates a new GoogleNativeAd RecordBuilder by copying an existing Builder */
  public static maestro.components.GoogleNativeAd.Builder newBuilder(maestro.components.GoogleNativeAd.Builder other) {
    return new maestro.components.GoogleNativeAd.Builder(other);
  }

  /** Creates a new GoogleNativeAd RecordBuilder by copying an existing GoogleNativeAd instance */
  public static maestro.components.GoogleNativeAd.Builder newBuilder(maestro.components.GoogleNativeAd other) {
    return new maestro.components.GoogleNativeAd.Builder(other);
  }

  /**
   * RecordBuilder for GoogleNativeAd instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GoogleNativeAd>
    implements org.apache.avro.data.RecordBuilder<GoogleNativeAd> {

    private CharSequence type;
    private CharSequence unit_id;
    private boolean location;
    private java.util.Map<CharSequence,java.util.List<CharSequence>> custom_targetting;
    private CharSequence cache_key;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.components.GoogleNativeAd.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.components.GoogleNativeAd.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.unit_id)) {
        this.unit_id = data().deepCopy(fields()[1].schema(), other.unit_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.custom_targetting)) {
        this.custom_targetting = data().deepCopy(fields()[3].schema(), other.custom_targetting);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cache_key)) {
        this.cache_key = data().deepCopy(fields()[4].schema(), other.cache_key);
        fieldSetFlags()[4] = true;
      }
    }

    /** Creates a Builder by copying an existing GoogleNativeAd instance */
    private Builder(maestro.components.GoogleNativeAd other) {
            super(maestro.components.GoogleNativeAd.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.unit_id)) {
        this.unit_id = data().deepCopy(fields()[1].schema(), other.unit_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.custom_targetting)) {
        this.custom_targetting = data().deepCopy(fields()[3].schema(), other.custom_targetting);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cache_key)) {
        this.cache_key = data().deepCopy(fields()[4].schema(), other.cache_key);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public maestro.components.GoogleNativeAd.Builder setType(CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'type' field */
    public maestro.components.GoogleNativeAd.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'unit_id' field */
    public CharSequence getUnitId() {
      return unit_id;
    }

    /** Sets the value of the 'unit_id' field */
    public maestro.components.GoogleNativeAd.Builder setUnitId(CharSequence value) {
      validate(fields()[1], value);
      this.unit_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'unit_id' field has been set */
    public boolean hasUnitId() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'unit_id' field */
    public maestro.components.GoogleNativeAd.Builder clearUnitId() {
      unit_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'location' field */
    public Boolean getLocation() {
      return location;
    }

    /** Sets the value of the 'location' field */
    public maestro.components.GoogleNativeAd.Builder setLocation(boolean value) {
      validate(fields()[2], value);
      this.location = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'location' field has been set */
    public boolean hasLocation() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'location' field */
    public maestro.components.GoogleNativeAd.Builder clearLocation() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'custom_targetting' field */
    public java.util.Map<CharSequence,java.util.List<CharSequence>> getCustomTargetting() {
      return custom_targetting;
    }

    /** Sets the value of the 'custom_targetting' field */
    public maestro.components.GoogleNativeAd.Builder setCustomTargetting(java.util.Map<CharSequence,java.util.List<CharSequence>> value) {
      validate(fields()[3], value);
      this.custom_targetting = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'custom_targetting' field has been set */
    public boolean hasCustomTargetting() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'custom_targetting' field */
    public maestro.components.GoogleNativeAd.Builder clearCustomTargetting() {
      custom_targetting = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'cache_key' field */
    public CharSequence getCacheKey() {
      return cache_key;
    }

    /** Sets the value of the 'cache_key' field */
    public maestro.components.GoogleNativeAd.Builder setCacheKey(CharSequence value) {
      validate(fields()[4], value);
      this.cache_key = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'cache_key' field has been set */
    public boolean hasCacheKey() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'cache_key' field */
    public maestro.components.GoogleNativeAd.Builder clearCacheKey() {
      cache_key = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public GoogleNativeAd build() {
      try {
        GoogleNativeAd record = new GoogleNativeAd();
        record.type = fieldSetFlags()[0] ? this.type : (CharSequence) defaultValue(fields()[0]);
        record.unit_id = fieldSetFlags()[1] ? this.unit_id : (CharSequence) defaultValue(fields()[1]);
        record.location = fieldSetFlags()[2] ? this.location : (Boolean) defaultValue(fields()[2]);
        record.custom_targetting = fieldSetFlags()[3] ? this.custom_targetting : (java.util.Map<CharSequence,java.util.List<CharSequence>>) defaultValue(fields()[3]);
        record.cache_key = fieldSetFlags()[4] ? this.cache_key : (CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
