/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.components;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ItemHighlights extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemHighlights\",\"namespace\":\"maestro.components\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.ItemHighlights\"},{\"name\":\"background_image_url\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"carousel\",\"type\":{\"type\":\"record\",\"name\":\"FlyerItemCarousel\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.FlyerItemCarousel\"},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"FlyerItem\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.FlyerItem\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"flyer_id\",\"type\":\"int\"},{\"name\":\"style\",\"type\":[\"null\",\"string\"],\"default\":null}]}}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence type;
  @Deprecated public CharSequence background_image_url;
  @Deprecated public CharSequence label;
  @Deprecated public maestro.components.FlyerItemCarousel carousel;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemHighlights() {}

  /**
   * All-args constructor.
   */
  public ItemHighlights(CharSequence type, CharSequence background_image_url, CharSequence label, maestro.components.FlyerItemCarousel carousel) {
    this.type = type;
    this.background_image_url = background_image_url;
    this.label = label;
    this.carousel = carousel;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return background_image_url;
    case 2: return label;
    case 3: return carousel;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: type = (CharSequence)value$; break;
    case 1: background_image_url = (CharSequence)value$; break;
    case 2: label = (CharSequence)value$; break;
    case 3: carousel = (maestro.components.FlyerItemCarousel)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'background_image_url' field.
   */
  public CharSequence getBackgroundImageUrl() {
    return background_image_url;
  }

  /**
   * Sets the value of the 'background_image_url' field.
   * @param value the value to set.
   */
  public void setBackgroundImageUrl(CharSequence value) {
    this.background_image_url = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'carousel' field.
   */
  public maestro.components.FlyerItemCarousel getCarousel() {
    return carousel;
  }

  /**
   * Sets the value of the 'carousel' field.
   * @param value the value to set.
   */
  public void setCarousel(maestro.components.FlyerItemCarousel value) {
    this.carousel = value;
  }

  /** Creates a new ItemHighlights RecordBuilder */
  public static maestro.components.ItemHighlights.Builder newBuilder() {
    return new maestro.components.ItemHighlights.Builder();
  }

  /** Creates a new ItemHighlights RecordBuilder by copying an existing Builder */
  public static maestro.components.ItemHighlights.Builder newBuilder(maestro.components.ItemHighlights.Builder other) {
    return new maestro.components.ItemHighlights.Builder(other);
  }

  /** Creates a new ItemHighlights RecordBuilder by copying an existing ItemHighlights instance */
  public static maestro.components.ItemHighlights.Builder newBuilder(maestro.components.ItemHighlights other) {
    return new maestro.components.ItemHighlights.Builder(other);
  }

  /**
   * RecordBuilder for ItemHighlights instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemHighlights>
    implements org.apache.avro.data.RecordBuilder<ItemHighlights> {

    private CharSequence type;
    private CharSequence background_image_url;
    private CharSequence label;
    private maestro.components.FlyerItemCarousel carousel;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.components.ItemHighlights.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.components.ItemHighlights.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.background_image_url)) {
        this.background_image_url = data().deepCopy(fields()[1].schema(), other.background_image_url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.carousel)) {
        this.carousel = data().deepCopy(fields()[3].schema(), other.carousel);
        fieldSetFlags()[3] = true;
      }
    }

    /** Creates a Builder by copying an existing ItemHighlights instance */
    private Builder(maestro.components.ItemHighlights other) {
            super(maestro.components.ItemHighlights.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.background_image_url)) {
        this.background_image_url = data().deepCopy(fields()[1].schema(), other.background_image_url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.carousel)) {
        this.carousel = data().deepCopy(fields()[3].schema(), other.carousel);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public maestro.components.ItemHighlights.Builder setType(CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'type' field */
    public maestro.components.ItemHighlights.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'background_image_url' field */
    public CharSequence getBackgroundImageUrl() {
      return background_image_url;
    }

    /** Sets the value of the 'background_image_url' field */
    public maestro.components.ItemHighlights.Builder setBackgroundImageUrl(CharSequence value) {
      validate(fields()[1], value);
      this.background_image_url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'background_image_url' field has been set */
    public boolean hasBackgroundImageUrl() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'background_image_url' field */
    public maestro.components.ItemHighlights.Builder clearBackgroundImageUrl() {
      background_image_url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public CharSequence getLabel() {
      return label;
    }

    /** Sets the value of the 'label' field */
    public maestro.components.ItemHighlights.Builder setLabel(CharSequence value) {
      validate(fields()[2], value);
      this.label = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'label' field */
    public maestro.components.ItemHighlights.Builder clearLabel() {
      label = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'carousel' field */
    public maestro.components.FlyerItemCarousel getCarousel() {
      return carousel;
    }

    /** Sets the value of the 'carousel' field */
    public maestro.components.ItemHighlights.Builder setCarousel(maestro.components.FlyerItemCarousel value) {
      validate(fields()[3], value);
      this.carousel = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'carousel' field has been set */
    public boolean hasCarousel() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'carousel' field */
    public maestro.components.ItemHighlights.Builder clearCarousel() {
      carousel = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ItemHighlights build() {
      try {
        ItemHighlights record = new ItemHighlights();
        record.type = fieldSetFlags()[0] ? this.type : (CharSequence) defaultValue(fields()[0]);
        record.background_image_url = fieldSetFlags()[1] ? this.background_image_url : (CharSequence) defaultValue(fields()[1]);
        record.label = fieldSetFlags()[2] ? this.label : (CharSequence) defaultValue(fields()[2]);
        record.carousel = fieldSetFlags()[3] ? this.carousel : (maestro.components.FlyerItemCarousel) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
