/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.components;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NavigationCarousel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NavigationCarousel\",\"namespace\":\"maestro.components\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.NavigationCarousel\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NavigationCarouselItem\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.components.NavigationCarouselItem\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"image_url\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"link\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DealCategory\",\"namespace\":\"maestro.common\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.common.DealCategory\"},{\"name\":\"category_id\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"BrowseCategory\",\"namespace\":\"maestro.common\",\"doc\":\"A Browse Category component describes a category of slots that can appear in the Browse Layout. A default category value of null will be used to render the Explore category of slots in the Browse Layout. Other category values of nearby, alphabetical, latest, favourites, and stackid_<id> (where <id> respresents the integer id value of a stack) will be used to render corresponding Nearby, A-Z, Latest, Favourites, and stack categories of slots.\",\"fields\":[{\"name\":\"type\",\"type\":\"string\",\"default\":\"maestro.common.BrowseCategory\"},{\"name\":\"category\",\"type\":\"string\"}]}]}]}}},{\"name\":\"initial_item_index\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence type;
  @Deprecated public java.util.List<maestro.components.NavigationCarouselItem> items;
  @Deprecated public Integer initial_item_index;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NavigationCarousel() {}

  /**
   * All-args constructor.
   */
  public NavigationCarousel(CharSequence type, java.util.List<maestro.components.NavigationCarouselItem> items, Integer initial_item_index) {
    this.type = type;
    this.items = items;
    this.initial_item_index = initial_item_index;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return items;
    case 2: return initial_item_index;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: type = (CharSequence)value$; break;
    case 1: items = (java.util.List<maestro.components.NavigationCarouselItem>)value$; break;
    case 2: initial_item_index = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'items' field.
   */
  public java.util.List<maestro.components.NavigationCarouselItem> getItems() {
    return items;
  }

  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<maestro.components.NavigationCarouselItem> value) {
    this.items = value;
  }

  /**
   * Gets the value of the 'initial_item_index' field.
   */
  public Integer getInitialItemIndex() {
    return initial_item_index;
  }

  /**
   * Sets the value of the 'initial_item_index' field.
   * @param value the value to set.
   */
  public void setInitialItemIndex(Integer value) {
    this.initial_item_index = value;
  }

  /** Creates a new NavigationCarousel RecordBuilder */
  public static maestro.components.NavigationCarousel.Builder newBuilder() {
    return new maestro.components.NavigationCarousel.Builder();
  }

  /** Creates a new NavigationCarousel RecordBuilder by copying an existing Builder */
  public static maestro.components.NavigationCarousel.Builder newBuilder(maestro.components.NavigationCarousel.Builder other) {
    return new maestro.components.NavigationCarousel.Builder(other);
  }

  /** Creates a new NavigationCarousel RecordBuilder by copying an existing NavigationCarousel instance */
  public static maestro.components.NavigationCarousel.Builder newBuilder(maestro.components.NavigationCarousel other) {
    return new maestro.components.NavigationCarousel.Builder(other);
  }

  /**
   * RecordBuilder for NavigationCarousel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NavigationCarousel>
    implements org.apache.avro.data.RecordBuilder<NavigationCarousel> {

    private CharSequence type;
    private java.util.List<maestro.components.NavigationCarouselItem> items;
    private Integer initial_item_index;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.components.NavigationCarousel.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.components.NavigationCarousel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.initial_item_index)) {
        this.initial_item_index = data().deepCopy(fields()[2].schema(), other.initial_item_index);
        fieldSetFlags()[2] = true;
      }
    }

    /** Creates a Builder by copying an existing NavigationCarousel instance */
    private Builder(maestro.components.NavigationCarousel other) {
            super(maestro.components.NavigationCarousel.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.initial_item_index)) {
        this.initial_item_index = data().deepCopy(fields()[2].schema(), other.initial_item_index);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public maestro.components.NavigationCarousel.Builder setType(CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'type' field */
    public maestro.components.NavigationCarousel.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'items' field */
    public java.util.List<maestro.components.NavigationCarouselItem> getItems() {
      return items;
    }

    /** Sets the value of the 'items' field */
    public maestro.components.NavigationCarousel.Builder setItems(java.util.List<maestro.components.NavigationCarouselItem> value) {
      validate(fields()[1], value);
      this.items = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'items' field has been set */
    public boolean hasItems() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'items' field */
    public maestro.components.NavigationCarousel.Builder clearItems() {
      items = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'initial_item_index' field */
    public Integer getInitialItemIndex() {
      return initial_item_index;
    }

    /** Sets the value of the 'initial_item_index' field */
    public maestro.components.NavigationCarousel.Builder setInitialItemIndex(Integer value) {
      validate(fields()[2], value);
      this.initial_item_index = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'initial_item_index' field has been set */
    public boolean hasInitialItemIndex() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'initial_item_index' field */
    public maestro.components.NavigationCarousel.Builder clearInitialItemIndex() {
      initial_item_index = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public NavigationCarousel build() {
      try {
        NavigationCarousel record = new NavigationCarousel();
        record.type = fieldSetFlags()[0] ? this.type : (CharSequence) defaultValue(fields()[0]);
        record.items = fieldSetFlags()[1] ? this.items : (java.util.List<maestro.components.NavigationCarouselItem>) defaultValue(fields()[1]);
        record.initial_item_index = fieldSetFlags()[2] ? this.initial_item_index : (Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
