/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package maestro.components;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PopularCarousel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PopularCarousel\",\"namespace\":\"maestro.components\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PopularCarousel() {}

  /**
   * All-args constructor.
   */
  public PopularCarousel(CharSequence name) {
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: name = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /** Creates a new PopularCarousel RecordBuilder */
  public static maestro.components.PopularCarousel.Builder newBuilder() {
    return new maestro.components.PopularCarousel.Builder();
  }

  /** Creates a new PopularCarousel RecordBuilder by copying an existing Builder */
  public static maestro.components.PopularCarousel.Builder newBuilder(maestro.components.PopularCarousel.Builder other) {
    return new maestro.components.PopularCarousel.Builder(other);
  }

  /** Creates a new PopularCarousel RecordBuilder by copying an existing PopularCarousel instance */
  public static maestro.components.PopularCarousel.Builder newBuilder(maestro.components.PopularCarousel other) {
    return new maestro.components.PopularCarousel.Builder(other);
  }

  /**
   * RecordBuilder for PopularCarousel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PopularCarousel>
    implements org.apache.avro.data.RecordBuilder<PopularCarousel> {

    private CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(maestro.components.PopularCarousel.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(maestro.components.PopularCarousel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }

    /** Creates a Builder by copying an existing PopularCarousel instance */
    private Builder(maestro.components.PopularCarousel other) {
            super(maestro.components.PopularCarousel.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public CharSequence getName() {
      return name;
    }

    /** Sets the value of the 'name' field */
    public maestro.components.PopularCarousel.Builder setName(CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'name' field */
    public maestro.components.PopularCarousel.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public PopularCarousel build() {
      try {
        PopularCarousel record = new PopularCarousel();
        record.name = fieldSetFlags()[0] ? this.name : (CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
